# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fragaria.cz
email: info@fragaria.cz
description: >
    We are a software development company based in Czech Republic. Our
    specialization are state-of-the-art web without compromises applications
    that you can rely on. JavaScript, Python, NodeJS, Angular or Vue.js... we know it all.
keywords: fragaria, software, vývoj software, webové aplikace, python, javascript, angular, elasticsearch, html, css
url: "https://fragaria.cz" # the base hostname & protocol for your site
baseurl: "/website/"
logo: "/assets/logo.svg" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo

sass:
    style: compressed
    sass_dir: _sass

# Build settings
markdown: kramdown

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate
    - jekyll-archives

exclude:
    - Dockerfile
    - docker-compose.yml
    - readme.md
    - Gemfile
    - Gemfile.lock
    - __design
    - .sass-cache

permalink: /blog/:year/:month/:day/:title/

# --------------------------- plugins ------------------------------------------

paginate_path: "/blog/archive/:num/"
paginate: 12

jekyll-archives:
    enabled:
        - year
        - month
        - tags
    layout: scoped-archive
    permalinks:
        year: /blog/archive/year/:year/
        month: /blog/archive/month/:year-:month/
        tag: /blog/archive/tag/:name/

cloudinary:
    cloud_name: fragaria
    cloud_path_prefix: fragaria.cz/

# ---------------------- custom configuration ----------------------------------

company:
    website_title: fragaria.cz
    official_name: Fragaria s.r.o.
    phone: +420 222 581 311
    email: info@fragaria.cz
    # contact_email: info@fragaria.cz
    contact_email: xaralis93@gmail.com
    ico: 48590151
    dic: CZ48590151
    account_nr: 2700620429/2010
    listed_at: >
        Spisová značka: C 18340 vedená u Městského soudu v Praze
    address:
        residence:
            line1: Ječná 507/6
            line2: 120 00 Praha 2
            line3: Czech Republic
            map_link: https://www.google.com/maps/place/Fragaria+s.r.o./@50.0754397,14.420427,17z/data=!4m13!1m7!3m6!1s0x470b94f4a0a239d7:0xb2eea226236a6892!2zSmXEjW7DoSA1MDcvNiwgMTIwIDAwIE5vdsOpIE3Em3N0bw!3b1!8m2!3d50.0754363!4d14.4226157!3m4!1s0x470b94f4a0a6806f:0x4cd2eac776b26943!8m2!3d50.07548!4d14.42264
        billing:
            line1: Pampelišková 2013/8
            line2: 106 00 Praha 10
            line3: Czech Republic
    social:
        twitter: fragariacz
        linkedin: fragaria-ltd-
        gplus: FragariaCz
        github: fragaria

